<?php

namespace App\Modules\Master\Base\Enums;

/**
 * バッチID一覧
 */
enum BatchListEnum: string implements BatchListEnumInterface
{
    case IMPCSV_CUSTOMER = 'impcsv_customer';
    case EXPCSV_CUSTOMER = 'expcsv_customer';
    case CSV_OUTPUT_NECSM0120 = 'csv_output_NECSM0120';
    case CUSTOMER_ERASE = 'customer-erase';
    case IMPCSV_ORDER = 'impcsv_order';
    case IMPCSV_ORDER_FUTURESHOP = 'impcsv_order_futureshop';
    case EXPCSV_ORDER_DETAIL = 'expcsv_order_detail';
    case EXPCSV_ORDER_SKU = 'expcsv_order_sku';
    case EXPCSV_ORDER_UPDATE = 'expcsv_order_update';
    case IMPCSV_ORDER_UPDATE = 'impcsv_order_update';
    case CHANGE_DELIVERY_TYPE = 'change_delivery_type';
    case CHANGE_DELI_HOPE_DATE = 'change_deli_hope_date';
    case CHANGE_DELI_PLAN_DATE = 'change_deli_plan_date';
    case CHANGE_OPERATOR_COMMENT = 'change_operator_comment';
    case CHANGE_ORDER_TAG = 'change_order_tag';
    case CHANGE_PROGRESS = 'change_progress';
    case RESERVE_STOCK = 'reserve_stock';
    case SEND_TEMPLATE_MAIL = 'send_template_mail';
    case SEND_RECIPT_MAIL = 'send_recipt_mail';
    case AUTO_DELIVERY = 'auto-delivery';
    case DELETE_COMPLETE_ORDER = 'delete-complete-order';
    case EXPCSV_PAYMENT_AUTH_CSV = 'expcsv_payment_auth_csv';
    case IMPCSV_PAYMENT_AUTH = 'impcsv_payment_auth';
    case EXPCSV_PAYMENT_DELIVERY_RESULT = 'expcsv_payment_delivery_result';
    case SET_PAYMENT = 'set_payment';
    case IMPCSV_PAYMENT_RESULT_STDIN = 'impcsv_payment_result_stdin';
    case IMPCSV_PAYMENT_RESULT_JNBIN = 'impcsv_payment_result_jnbin';
    case NEIJBD010C = 'NEIJBD010C';
    case NEIJBA010C = 'NEIJBA010C';
    case NEIJBB010C = 'NEIJBB010C';
    case NEIJBA020C = 'NEIJBA020C';
    case NEIJBB020C = 'NEIJBB020C';
    case NEIJBA030C = 'NEIJBA030C';
    case NEIJBB030C = 'NEIJBB030C';
    case NEIJBA121C = 'NEIJBA121C';
    case NEIJBA321C = 'NEIJBA321C';
    case NEIJBA421C = 'NEIJBA421C';
    case NEIJBA521C = 'NEIJBA521C';
    case NEIJBA621C = 'NEIJBA621C';
    case NEIJBA721C = 'NEIJBA721C';
    case NEIJBB121C = 'NEIJBB121C';
    case NEIJBB321C = 'NEIJBB321C';
    case NEIJBB421C = 'NEIJBB421C';
    case NEIJBB521C = 'NEIJBB521C';
    case NEIJBB621C = 'NEIJBB621C';
    case NEIJBB721C = 'NEIJBB721C';
    case EXPCSV_WAREHOUSE_STOCK = 'expcsv_warehouse_stock';
    case EXPCSV_ITEM_STOCK = 'expcsv_item_stock';
    case EXPCSV_STOCK_HISTORY = 'expcsv_stock_history';
    case IMPCSV_WAREHOUSE_STOCK = 'impcsv_warehouse_stock';
    case STOCK_AGGREGATE = 'stock_aggregate';
    case STOCK_CORRECT = 'stock_correct';
    case ENABLE_VOL_CORRECT = 'enable_vol_correct';
    case DEL_STOCK_COMPLETE = 'del_stock_complete';
    case EXPCSV_DELIVERY_10 = 'expcsv_delivery_10';
    case EXPCSV_DELIVERY_20 = 'expcsv_delivery_20';
    case EXPCSV_DELIVERY_21 = 'expcsv_delivery_21';
    case EXPCSV_DELIVERY_30 = 'expcsv_delivery_30';
    case EXPCSV_DELIVERY_31 = 'expcsv_delivery_31';
    case EXPCSV_DELIVERY_40 = 'expcsv_delivery_40';
    case EXPCSV_DELIVERY_50 = 'expcsv_delivery_50';
    case EXPCSV_DELIVERY_60 = 'expcsv_delivery_60';
    case EXPPDF_TOTAL_PICKING = 'exppdf_total_picking';
    case EXPPDF_DETAIL_PICKING = 'exppdf_detail_picking';
    case EXPPDF_SUBMISSION = 'exppdf_submission';
    case IMPCSV_DELIVERY_10 = 'impcsv_delivery_10';
    case IMPCSV_DELIVERY_20 = 'impcsv_delivery_20';
    case IMPCSV_DELIVERY_21 = 'impcsv_delivery_21';
    case IMPCSV_DELIVERY_30 = 'impcsv_delivery_30';
    case IMPCSV_DELIVERY_31 = 'impcsv_delivery_31';
    case IMPCSV_DELIVERY_40 = 'impcsv_delivery_40';
    case IMPCSV_DELIVERY_50 = 'impcsv_delivery_50';
    case IMPCSV_DELIVERY_60 = 'impcsv_delivery_60';
    case EXPCSV_ORDER_PLACEMENTS = 'expcsv_order_placements';
    case EXPCSV_PURCHASE = 'expcsv_purchase';
    case IMPCSV_ORDER_PLACEMENTS = 'impcsv_order_placements';
    case NEGJBA010C = 'NEGJBA010C';
    case NEGJBA111C = 'NEGJBA111C';
    case NEGJBA311C = 'NEGJBA311C';
    case NEGJBA411C = 'NEGJBA411C';
    case NEGJBA511C = 'NEGJBA511C';
    case NEGJBA020C = 'NEGJBA020C';
    case NEGJBA121C = 'NEGJBA121C';
    case NEGJBA421C = 'NEGJBA421C';
    case NEGJBH711C = 'NEGJBH711C';
    case NEGJBA030C = 'NEGJBA030C';
    case NEGJBA131C = 'NEGJBA131C';
    case NEGJBA431C = 'NEGJBA431C';
    case NEGJBB010C = 'NEGJBB010C';
    case NEGJBB111C = 'NEGJBB111C';
    case NEGJBB311C = 'NEGJBB311C';
    case NEGJBB411C = 'NEGJBB411C';
    case NEGJBB511C = 'NEGJBB511C';
    case NEGJBB711C = 'NEGJBB711C';
    case NEGJBC010C = 'NEGJBC010C';
    case NEGJBC111C = 'NEGJBC111C';
    case NEGJBC311C = 'NEGJBC311C';
    case NEGJBC411C = 'NEGJBC411C';
    case NEGJBC511C = 'NEGJBC511C';
    case NEGJBC711C = 'NEGJBC711C';
    case NEGJBD010C = 'NEGJBD010C';
    case NEGJBD011C = 'NEGJBD011C';
    case NEGJBD020C = 'NEGJBD020C';
    case NEGJBD021C = 'NEGJBD021C';
    case NEGJBD030C = 'NEGJBD030C';
    case NEGJBD031C = 'NEGJBD031C';
    case NEGJBD131C = 'NEGJBD131C';
    case NEGJBD331C = 'NEGJBD331C';
    case NEGJBD431C = 'NEGJBD431C';
    case NEGJBD531C = 'NEGJBD531C';
    case NEGJBD631C = 'NEGJBD631C';
    case NEGJBD731C = 'NEGJBD731C';
    case NEGJBD040C = 'NEGJBD040C';
    case NEGJBD041C = 'NEGJBD041C';
    case NEGJBD341C = 'NEGJBD341C';
    case NEGJBD050C = 'NEGJBD050C';
    case NEGJBD051C = 'NEGJBD051C';
    case NEGJBD151C = 'NEGJBD151C';
    case NEGJBD351C = 'NEGJBD351C';
    case NEGJBD451C = 'NEGJBD451C';
    case NEGJBD551C = 'NEGJBD551C';
    case NEGJBD651C = 'NEGJBD651C';
    case NEGJBD751C = 'NEGJBD751C';
    case NEGJBD060C = 'NEGJBD060C';
    case NEGJBD061C = 'NEGJBD061C';
    case NEGJBF010C = 'NEGJBF010C';
    case NEGJBG010C = 'NEGJBG010C';
    case NEGJBG111C = 'NEGJBG111C';
    case NEGJBG020C = 'NEGJBG020C';
    case NEGJBG121C = 'NEGJBG121C';
    case IMPDAT_PAYMENT_CREDIT = 'impdat_payment_credit';
    case IMPDAT_PAYMENT_CVS = 'Impdat_payment_cvs';
    case IMPDAT_PAYMENT_COLLECT = 'Impdat_payment_collect';

    public function label(): string
    {
        return match($this) {
            self::IMPCSV_CUSTOMER => '顧客取込',
            self::EXPCSV_CUSTOMER => '顧客出力',
            self::CSV_OUTPUT_NECSM0120 => '顧客対応履歴出力',
            self::CUSTOMER_ERASE => '顧客個人情報削除',
            self::IMPCSV_ORDER => '受注取込',
            self::IMPCSV_ORDER_FUTURESHOP => '受注取込(futureshop)',
            self::EXPCSV_ORDER_DETAIL => '受注明細CSV出力',
            self::EXPCSV_ORDER_SKU => '受注商品CSV出力',
            self::EXPCSV_ORDER_UPDATE => '受注一括編集出力',
            self::IMPCSV_ORDER_UPDATE => '受注一括編集取込',
            self::CHANGE_DELIVERY_TYPE => '一括配送方法変更',
            self::CHANGE_DELI_HOPE_DATE => '一括配送希望日変更',
            self::CHANGE_DELI_PLAN_DATE => '一括出荷予定日変更',
            self::CHANGE_OPERATOR_COMMENT => '一括社内メモ変更',
            self::CHANGE_ORDER_TAG => '一括受注タグ変更',
            self::CHANGE_PROGRESS => '進捗区分変更',
            self::RESERVE_STOCK => '受注一括在庫引当',
            self::SEND_TEMPLATE_MAIL => 'メール一括送信',
            self::SEND_RECIPT_MAIL => '領収書メール一括送信',
            self::AUTO_DELIVERY => '自動出荷',
            self::DELETE_COMPLETE_ORDER => '受注完了データ削除',
            self::EXPCSV_PAYMENT_AUTH_CSV => '与信データ出力',
            self::IMPCSV_PAYMENT_AUTH => '与信結果取込',
            self::EXPCSV_PAYMENT_DELIVERY_RESULT => '出荷報告データ出力',
            self::SET_PAYMENT => '全額入金',
            self::IMPCSV_PAYMENT_RESULT_STDIN => '銀行入金（標準形式）取込',
            self::IMPCSV_PAYMENT_RESULT_JNBIN => '銀行入金（JNB形式）取込',
            self::NEIJBD010C => 'EC在庫再計算',
            self::NEIJBA010C => 'SKUマスタCSV出力',
            self::NEIJBB010C => 'SKUマスタCSV取込',
            self::NEIJBA020C => 'ページマスタCSV出力',
            self::NEIJBB020C => 'ページマスタCSV取込',
            self::NEIJBA030C => 'ページオプションCSV出力',
            self::NEIJBB030C => 'ページオプションCSV取込',
            self::NEIJBA121C => 'ECページ(Yahoo)CSV出力',
            self::NEIJBA321C => 'ECページ(楽天)CSV出力',
            self::NEIJBA421C => 'ECページ(Amazon)CSV出力',
            self::NEIJBA521C => 'ECページ(Wowma)CSV出力',
            self::NEIJBA621C => 'ECページ(店舗)CSV出力',
            self::NEIJBA721C => 'ECページ(futureshop)CSV出力',
            self::NEIJBB121C => 'ECページ(Yahoo)CSV取込',
            self::NEIJBB321C => 'ECページ(楽天)CSV取込',
            self::NEIJBB421C => 'ECページ(Amazon)CSV取込',
            self::NEIJBB521C => 'ECページ(Wowma)CSV取込',
            self::NEIJBB621C => 'ECページ(店舗)CSV取込',
            self::NEIJBB721C => 'ECページ(futuresho)CSV取込',
            self::EXPCSV_WAREHOUSE_STOCK => '倉庫在庫CSV出力',
            self::EXPCSV_ITEM_STOCK => '商品在庫CSV出力',
            self::EXPCSV_STOCK_HISTORY => '在庫履歴CSV出力',
            self::IMPCSV_WAREHOUSE_STOCK => '倉庫商品在庫CSV取込',
            self::STOCK_AGGREGATE => '在庫集計',
            self::STOCK_CORRECT => '在庫マスタ洗い替え',
            self::ENABLE_VOL_CORRECT => '販売可能数洗い替え',
            self::DEL_STOCK_COMPLETE => '引当完了データ削除',
            self::EXPCSV_DELIVERY_10 => '出荷データ出力(B2Ver6用)',
            self::EXPCSV_DELIVERY_20 => '出荷データ出力(e飛伝Ⅱ用)',
            self::EXPCSV_DELIVERY_21 => '出荷データ出力(e飛伝Pro用)',
            self::EXPCSV_DELIVERY_30 => '出荷データ出力(ゆうプリR用)',
            self::EXPCSV_DELIVERY_31 => '出荷データ出力(ゆうプリSky用)',
            self::EXPCSV_DELIVERY_40 => '出荷データ出力(i-Star2用)',
            self::EXPCSV_DELIVERY_50 => '出荷データ出力(カンガルーマジックⅡ用)',
            self::EXPCSV_DELIVERY_60 => '出荷データ出力(eシェルパモール-標準形式)',
            self::EXPPDF_TOTAL_PICKING => 'トータルピッキングリスト出力',
            self::EXPPDF_DETAIL_PICKING => '個別ピッキングリスト出力',
            self::EXPPDF_SUBMISSION => '納品書出力',
            self::IMPCSV_DELIVERY_10 => '出荷データ取込(B2Ver6用)',
            self::IMPCSV_DELIVERY_20 => '出荷データ取込(e飛伝Ⅱ用)',
            self::IMPCSV_DELIVERY_21 => '出荷データ取込(e飛伝Pro用)',
            self::IMPCSV_DELIVERY_30 => '出荷データ取込(ゆうプリR用)',
            self::IMPCSV_DELIVERY_31 => '出荷データ取込(ゆうプリSky用)',
            self::IMPCSV_DELIVERY_40 => '出荷データ取込(i-Star2用)',
            self::IMPCSV_DELIVERY_50 => '出荷データ取込(カンガルーマジックⅡ用)',
            self::IMPCSV_DELIVERY_60 => '出荷データ取込(eシェルパモール-標準形式)',
            self::EXPCSV_ORDER_PLACEMENTS => '発注情報CSV出力',
            self::EXPCSV_PURCHASE => '仕入情報CSV出力',
            self::IMPCSV_ORDER_PLACEMENTS => '発注CSV取込',
            self::NEGJBA010C => '受注連携JOB起動制御',
            self::NEGJBA111C => '受注(Yahoo)連携',
            self::NEGJBA311C => '受注(楽天)連携',
            self::NEGJBA411C => '受注(Amazon)連携',
            self::NEGJBA511C => '受注(Wowma)連携',
            self::NEGJBA020C => '受注速報連携JOB起動制御',
            self::NEGJBA121C => '受注速報(Yahoo)連携',
            self::NEGJBA421C => '受注速報(Amazon)',
            self::NEGJBH711C => '受注メール速報(futureshop)連携',
            self::NEGJBA030C => '受注速報訂正JOB起動制御',
            self::NEGJBA131C => '受注速報訂正(Yahoo)連携',
            self::NEGJBA431C => '受注速報訂正(Amazon)連携',
            self::NEGJBB010C => 'ECページ連携JOB起動制御',
            self::NEGJBB111C => 'ECページ(Yahoo)連携',
            self::NEGJBB311C => 'ECページ(楽天)連携',
            self::NEGJBB411C => 'ECページ(Amazon)連携',
            self::NEGJBB511C => 'ECページ(Wowma)連携',
            self::NEGJBB711C => 'ECページ(futureshop)連携',
            self::NEGJBC010C => 'EC在庫連携JOB起動制御',
            self::NEGJBC111C => 'EC在庫(Yahoo)連携',
            self::NEGJBC311C => 'EC在庫(楽天)連携',
            self::NEGJBC411C => 'EC在庫(Amazon)連携',
            self::NEGJBC511C => 'EC在庫(Wowma)連携',
            self::NEGJBC711C => 'EC在庫(futureshop)連携',
            self::NEGJBD010C => '受注登録連携JOB起動制御',
            self::NEGJBD011C => '注文登録(後払い.com)連携',
            self::NEGJBD020C => '受注変更連携JOB起動制御',
            self::NEGJBD021C => '注文変更(後払い.com)連携',
            self::NEGJBD030C => '受注キャンセル連携JOB起動制御',
            self::NEGJBD031C => '注文キャンセル(後払い.com)連携',
            self::NEGJBD131C => '注文キャンセル(Yahoo)連携',
            self::NEGJBD331C => '注文キャンセル(楽天)連携',
            self::NEGJBD431C => '注文キャンセル(Amazon)連携',
            self::NEGJBD531C => '注文キャンセル(Wowma)連携',
            self::NEGJBD631C => '注文キャンセル(店舗)連携',
            self::NEGJBD731C => '注文キャンセル(futureshop)連携',
            self::NEGJBD040C => '与信連携JOB起動制御',
            self::NEGJBD041C => '与信(後払い.com)連携',
            self::NEGJBD341C => '与信(楽天)連携',
            self::NEGJBD050C => '出荷報告連携JOB起動制御',
            self::NEGJBD051C => '出荷登録(後払い.com)連携',
            self::NEGJBD151C => '出荷登録(Yahoo)連携',
            self::NEGJBD351C => '出荷登録(楽天)連携',
            self::NEGJBD451C => '出荷登録(Amazon)連携',
            self::NEGJBD551C => '出荷登録(Wowma)連携',
            self::NEGJBD651C => '出荷登録(店舗)連携',
            self::NEGJBD751C => '出荷登録(futureshop)連携',
            self::NEGJBD060C => '実売上連携JOB起動制御',
            self::NEGJBD061C => '実売上(後払い.com)連携',
            self::NEGJBF010C => 'メール送信',
            self::NEGJBG010C => 'WMS(アップロード)連携JOB起動制御',
            self::NEGJBG111C => 'L-spark(アップロード)連携',
            self::NEGJBG020C => 'WMS(ダウンロード)連携JOB起動制御',
            self::NEGJBG121C => 'L-spark(ダウンロード)連携',
            self::IMPDAT_PAYMENT_CREDIT => 'クレジット入金取り込み',
            self::IMPDAT_PAYMENT_CVS => 'コンビニ・郵便振込取込',
            self::IMPDAT_PAYMENT_COLLECT => 'コレクト入金取込',
        };
    }
}
